load_data:
  raw_data: data/raw/insurance.csv
  process_data: data/processed/processed.csv

split_data:
  train_path: data/processed/train_insurance.csv
  test_path: data/processed/test_insurance.csv
  split_ratio: 0.250
  random_state: 0

reports:
  scores: reports/scores.json
  params: reports/params.json

log_dir: logs

target_data: expenses

model_dirs: saved_models

encoder: encoded.pkl

webapp_model: model.pkl

model:
  alpha: 0.9
  ccp_alpha: 0.0
  criterion: 'friedman_mse'
  learning_rate: 0.1
  loss: 'squared_error'
  max_depth: 3
  min_impurity_decrease: 0.0
  min_samples_leaf: 1
  min_samples_split: 2
  min_weight_fraction_leaf: 0.0
  n_estimators: 100
  random_state: 123
  subsample: 1.0
  tol: 0.0001
  validation_fraction: 0.1
  verbose: 0
  warm_start: False